'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const {promisify} = require('node:util');
const {execFile} = require('node:child_process');
const proxyquire = require('proxyquire');
const maven = require('../lib/ecosystems/maven');
const {NoLockfileError, ReferenceStore} = require('../lib/ecosystems/common');
const {
  tempDir, writeFiles, needsPosix, PATH_MAX, deepTempDir, unreadableEntry, startServer, makeZip, which,
} = require('./helpers');

const sha256 = data => crypto.createHash('sha256').update(data).digest('hex');
const hasJar = which('jar');

function pomProperties(groupId, artifactId, version) {
  return `#Generated by Maven\ngroupId=${groupId}\nartifactId=${artifactId}\nversion=${version}\n`;
}

/**
 * A jar (a zip) holding `files`.
 * @returns {Buffer}
 */
function makeJar(t, files) {
  return makeZip(Object.entries(files).map(([name, data]) => ({name, data})));
}

function libraryJar(t, coordinates, extra = {}) {
  const [groupId, artifactId, version] = coordinates.split(':');
  return makeJar(t, {
    [`META-INF/maven/${groupId}/${artifactId}/pom.properties`]: pomProperties(groupId, artifactId, version),
    [`${artifactId}/Main.class`]: `${groupId}:${artifactId}:${version}`,
    ...extra,
  });
}

test('detect finds the directories builds copy dependency jars into', t => {
  const root = tempDir(t);
  assert.deepEqual(maven.detect(root), []);
  writeFiles(root, {
    'target/lib/a.jar': '',
    'target/dependency/b.jar': '',
    'target/classes/App.class': '',
    'target/shop/WEB-INF/lib/c.jar': '',
    'target/app.jar': '',
    'lib/d.war': '',
    'libs/readme.txt': '',
    'build/install/app/lib/e.jar': '',
    'build/install/empty/bin/app': '',
    'build/libs/site/WEB-INF/lib/f.jar': '',
  });
  assert.deepEqual(maven.detect(root).sort(), [
    path.join(root, 'build', 'install', 'app', 'lib'),
    path.join(root, 'build', 'libs', 'site', 'WEB-INF', 'lib'),
    path.join(root, 'lib'),
    path.join(root, 'target', 'dependency'),
    path.join(root, 'target', 'lib'),
    path.join(root, 'target', 'shop', 'WEB-INF', 'lib'),
  ]);
  assert.equal(maven.installRoot('/srv/lib'), '/srv/lib');
  assert.deepEqual(maven.lockfiles, ['gradle/verification-metadata.xml', 'lockfile.json']);
});

test('coordinates reads the one pom.properties a jar declares', t => {
  assert.deepEqual(maven.coordinates(libraryJar(t, 'org.example:core:1.0')), {groupId: 'org.example', artifactId: 'core', version: '1.0'});
  const spaced = makeJar(t, {'META-INF/maven/g/a/pom.properties': ' groupId : g\r\nartifactId=a\r\n# comment\r\nversion= 2.0 \r\n'});
  assert.deepEqual(maven.coordinates(spaced), {groupId: 'g', artifactId: 'a', version: '2.0'});
  assert.equal(maven.coordinates(makeJar(t, {'a/A.class': 'x', 'META-INF/MANIFEST.MF': 'Manifest-Version: 1.0\n'})), null);
  // A shaded jar declares several artifacts: none is its own.
  assert.equal(maven.coordinates(libraryJar(t, 'org.example:fat:1.0', {'META-INF/maven/org.other/dep/pom.properties': pomProperties('org.other', 'dep', '3.0')})), null);
  assert.equal(maven.coordinates(makeJar(t, {'META-INF/maven/g/a/pom.properties': 'groupId=g\nartifactId=a\n'})), null);
  assert.equal(maven.coordinates(Buffer.from('not a zip')), null);
});

test('scan hashes each jar and lists everything else', {skip: needsPosix}, async t => {
  const directory = tempDir(t);
  const core = libraryJar(t, 'org.example:core:1.0');
  const plain = makeJar(t, {'x/X.class': 'x'});
  writeFiles(directory, {
    'core-1.0.jar': core, 'plain.jar': plain, 'SITE.WAR': plain, 'notes.txt': 'n', 'nested/inner.jar': plain,
  });
  fs.symlinkSync('core-1.0.jar', path.join(directory, 'link.jar'));

  const result = await maven.scan(directory);
  assert.deepEqual(result.errors, []);
  assert.deepEqual(result.packages, [
    {
      name: 'SITE.WAR', version: null, path: 'SITE.WAR', files: {'SITE.WAR': sha256(plain)}, meta: {},
    },
    {
      name: 'org.example:core', version: '1.0', path: 'core-1.0.jar', files: {'core-1.0.jar': sha256(core)}, meta: {coordinates: {groupId: 'org.example', artifactId: 'core', version: '1.0'}},
    },
    {
      name: 'plain.jar', version: null, path: 'plain.jar', files: {'plain.jar': sha256(plain)}, meta: {},
    },
  ]);
  assert.deepEqual(result.unaccounted, ['link.jar', 'nested/', 'notes.txt']);
});

test('scan reports a missing directory and jars it cannot read', async t => {
  const missing = await maven.scan(path.join(tempDir(t), 'lib'));
  assert.deepEqual(missing.errors, [{path: '.', error: 'ENOENT'}]);
  assert.deepEqual(missing.packages, []);

  if (!PATH_MAX) {
    return;
  }

  // The directory is readable, but its path with the jar name is longer than PATH_MAX.
  const name = `${'j'.repeat(240)}.jar`;
  const directory = unreadableEntry(deepTempDir(t), name);
  const result = await maven.scan(directory);
  assert.deepEqual(result.errors, [{path: name, error: 'ENAMETOOLONG'}]);
  assert.deepEqual(result.packages, []);
});

test('scan reports a jar that changes while it is hashed', async t => {
  const stubbed = proxyquire('../lib/ecosystems/maven', {
    '../file-tree': {
      async hashFile(file) {
        throw new Error(`File changed while hashing: ${file}`);
      },
    },
  });
  const directory = tempDir(t);
  writeFiles(directory, {'a.jar': 'x'});
  const result = await stubbed.scan(directory);
  assert.deepEqual(result.errors, [{path: 'a.jar', error: `File changed while hashing: ${path.join(directory, 'a.jar')}`}]);
});

test('parseVerificationMetadata collects the hashes Gradle pins for each artifact', () => {
  const a = 'a'.repeat(64);
  const b = 'B'.repeat(64);
  const c = 'c'.repeat(64);
  const pinned = maven.parseVerificationMetadata(`<?xml version="1.0" encoding="UTF-8"?>
<verification-metadata xmlns="https://schema.gradle.org/dependency-verification">
   <configuration>
      <verify-metadata>true</verify-metadata>
      <trusted-artifacts><trust group="org.example" name="app"/></trusted-artifacts>
   </configuration>
   <components>
      <component group="org.example" name="core" version="1.0">
         <artifact name="core-1.0.jar">
            <sha256 value="${a}" origin="Generated by Gradle"/>
            <sha512 value="${'f'.repeat(128)}"/>
            <also-trust value="${b}"/>
         </artifact>
         <artifact name="core-1.0.pom">
            <sha256 value="not-a-hash"/>
         </artifact>
         <artifact name="empty-1.0.jar"/>
         <artifact>
            <sha256 value="${'e'.repeat(64)}"/>
         </artifact>
         <artifact name="empty-1.0.jar">
            <sha256 origin="no value"/>
         </artifact>
      </component>
      <component group="org.other" name="core" version="1.0">
         <artifact name="core-1.0.jar">
            <sha256 value="${c}">
               <also-trust value="${a}"/>
            </sha256>
         </artifact>
      </component>
   </components>
   <sha256 value="${'d'.repeat(64)}"/>
</verification-metadata>
`);
  assert.deepEqual([...pinned.keys()], ['core-1.0.jar', 'core-1.0.pom', 'empty-1.0.jar']);
  assert.deepEqual([...pinned.get('core-1.0.jar')].sort(), [a, b.toLowerCase(), c]);
  assert.equal(pinned.get('core-1.0.pom').size, 0);
  assert.equal(pinned.get('empty-1.0.jar').size, 0);
});

test('parseMavenLockfile collects SHA-256 checksums from the dependency tree', () => {
  const a = 'a'.repeat(64);
  const b = 'b'.repeat(64);
  const pinned = maven.parseMavenLockfile({
    artifactID: 'app',
    dependencies: [
      {
        groupId: 'org.example',
        artifactId: 'core',
        version: '1.0',
        checksumAlgorithm: 'SHA-256',
        checksum: a.toUpperCase(),
        children: [
          {
            groupId: 'org.example', artifactId: 'native', version: '2.0', classifier: 'linux-x86_64', type: 'jar', checksumAlgorithm: 'sha256', checksum: b, children: [null, 'x'],
          },
          {
            groupId: 'org.example', artifactId: 'core', version: '1.0', checksumAlgorithm: 'SHA-256', checksum: b,
          },
        ],
      },
      {
        groupId: 'org.example', artifactId: 'web', version: '3.0', type: 'war', checksumAlgorithm: 'SHA-512', checksum: a,
      },
      {
        groupId: 'org.example', artifactId: 'short', version: '1.0', checksumAlgorithm: 'SHA-256', checksum: 'abc',
      },
      {groupId: 'org.example', artifactId: 'none', version: '1.0'},
      {
        groupId: 'org.example', artifactId: 'unsummed', version: '1.0', checksumAlgorithm: 'SHA-256',
      },
    ],
  });
  assert.deepEqual([...pinned.keys()], ['core-1.0.jar', 'native-2.0-linux-x86_64.jar']);
  assert.deepEqual([...pinned.get('core-1.0.jar')], [a, b]);
  assert.equal(maven.parseMavenLockfile({}).size, 0);
});

test('readLock prefers Gradle verification metadata, then maven-lockfile', t => {
  const repo = tempDir(t);
  assert.throws(() => maven.readLock(repo), NoLockfileError);
  assert.throws(() => maven.readLock(repo), /gradle\/verification-metadata\.xml, lockfile\.json/);
  writeFiles(repo, {
    'lockfile.json': JSON.stringify({
      dependencies: [{
        artifactId: 'core', version: '1.0', checksumAlgorithm: 'SHA-256', checksum: 'a'.repeat(64),
      }],
    }),
  });
  const lockfile = maven.readLock(repo);
  assert.equal(lockfile.format, 'maven-lockfile');
  assert.equal(lockfile.file, 'lockfile.json');
  assert.ok(lockfile.pinned.has('core-1.0.jar'));

  writeFiles(repo, {'gradle/verification-metadata.xml': '<verification-metadata><components/></verification-metadata>'});
  const gradle = maven.readLock(repo);
  assert.equal(gradle.format, 'gradle-verification-metadata');
  assert.equal(gradle.pinned.size, 0);
  assert.equal(maven.readLock(repo, {lockfile: 'lockfile.json'}).format, 'maven-lockfile');
  assert.throws(() => maven.readLock(repo, {lockfile: 'sub/lockfile.json'}), /\(sub\/lockfile\.json\)/);
});

test('compare checks pinned jars, and others against Maven Central', {skip: needsPosix}, async t => {
  const core = libraryJar(t, 'org.example:core:1.0');
  const util = libraryJar(t, 'org.example.util:util:2.0');
  const other = libraryJar(t, 'org.example:other:1.0');
  const server = await startServer(t, {
    '/org/example/util/util/2.0/util-2.0.jar': {body: util},
    '/org/example/other/1.0/other-1.0.jar': {body: libraryJar(t, 'org.example:other:1.0', {'extra.txt': 'different'})},
  });
  const directory = tempDir(t);
  writeFiles(directory, {
    'core-1.0.jar': core,
    'tampered-1.0.jar': core,
    'util-2.0.jar': util,
    'util-copy.jar': util,
    'other-1.0.jar': other,
    'gone-1.0.jar': libraryJar(t, 'org.example:gone:1.0'),
    'plain.jar': makeJar(t, {'x/X.class': 'x'}),
    'app.jar': makeJar(t, {'app/Main.class': 'x'}),
    'README.txt': 'r',
  });
  fs.symlinkSync('/srv/elsewhere/evil.jar', path.join(directory, 'linked-1.0.jar'));
  const lock = {
    pinned: new Map([
      ['core-1.0.jar', new Set([sha256(core)])],
      ['tampered-1.0.jar', new Set(['0'.repeat(64)])],
    ]),
  };
  const store = new ReferenceStore({urls: {maven: server.url}, httpOptions: {maxRetries: 0}});
  const scan = await maven.scan(directory);
  const result = await maven.compare({
    scan, lock, store, covered: file => file === 'app.jar',
  });

  const byPath = Object.fromEntries(result.findings.map(finding => [finding.path, finding]));
  assert.deepEqual(result.summary, {
    total: 7, verified: 3, bundled: 0, patched: 0, built: 0, failed: 3, unverifiable: 0, error: 1,
  });
  assert.equal(byPath['tampered-1.0.jar'].reason, 'the jar differs from the one the build pinned');
  assert.equal(byPath['plain.jar'].reason, 'the build pins no jar of this name, and the jar names no Maven coordinates');
  assert.equal(byPath['other-1.0.jar'].reason, 'the jar differs from Maven Central\'s for its coordinates');
  assert.equal(byPath['gone-1.0.jar'].status, 'error');
  assert.match(byPath['gone-1.0.jar'].reason, /^could not fetch it from Maven Central: .*404/);
  assert.equal(byPath['app.jar'], undefined);
  assert.deepEqual(result.issues, [
    {severity: 'warn', message: result.issues[0].message, items: ['util-2.0.jar', 'util-copy.jar']},
    {severity: 'fail', message: result.issues[1].message, items: ['linked-1.0.jar']},
    {severity: 'warn', message: 'Other files next to the jars', items: ['README.txt']},
  ]);
  assert.equal(result.passed, false);
  // Two jars with the same coordinates share one download.
  assert.equal(server.requests.filter(request => request.url.endsWith('/util-2.0.jar')).length, 1);
});

test('compare without a lock checks every jar against Maven Central', async t => {
  const core = libraryJar(t, 'org.example:core:1.0');
  const server = await startServer(t, {'/org/example/core/1.0/core-1.0.jar': {body: core}});
  const directory = tempDir(t);
  writeFiles(directory, {'core-1.0.jar': core});
  const result = await maven.compare({scan: await maven.scan(directory), lock: null, store: new ReferenceStore({urls: {maven: server.url}})});
  assert.equal(result.passed, true);
  assert.equal(result.summary.verified, 1);
  assert.deepEqual(result.issues.map(issue => issue.severity), ['warn']);
});

test('a Gradle build with dependency verification verifies', {skip: !(which('gradle') && hasJar && which('javac')) && 'gradle, jar or javac is not installed', timeout: 300_000}, async t => {
  const work = tempDir(t);
  const repository = path.join(work, 'repo');
  const artifact = path.join(repository, 'com', 'example', 'greeter', '1.0');
  writeFiles(work, {
    'greeter/src/com/example/Greeter.java': 'package com.example;\npublic class Greeter { public static String hello() { return "hi"; } }\n',
    'greeter/classes/META-INF/maven/com.example/greeter/pom.properties': pomProperties('com.example', 'greeter', '1.0'),
    'repo/com/example/greeter/1.0/greeter-1.0.pom': '<project><modelVersion>4.0.0</modelVersion><groupId>com.example</groupId><artifactId>greeter</artifactId><version>1.0</version></project>\n',
    'app/settings.gradle': 'rootProject.name = \'app\'\n',
    'app/build.gradle': [
      'plugins { id \'application\' }',
      `repositories { maven { url = uri('${repository}') } }`,
      'dependencies { implementation \'com.example:greeter:1.0\' }',
      'application { mainClass = \'app.Main\' }',
      '',
    ].join('\n'),
    'app/src/main/java/app/Main.java': 'package app;\npublic class Main { public static void main(String[] args) { System.out.println(com.example.Greeter.hello()); } }\n',
  });
  const run = promisify(execFile);
  await run('javac', ['-d', path.join(work, 'greeter', 'classes'), path.join(work, 'greeter', 'src', 'com', 'example', 'Greeter.java')]);
  await run('jar', ['cf', path.join(artifact, 'greeter-1.0.jar'), '-C', path.join(work, 'greeter', 'classes'), '.']);
  const app = path.join(work, 'app');
  await run('gradle', ['--offline', '--no-daemon', '--quiet', '--write-verification-metadata', 'sha256', 'installDist'], {
    cwd: app, env: {...process.env, GRADLE_USER_HOME: path.join(work, 'gradle-home')}, maxBuffer: 64 * 1024 * 1024,
  });

  const lib = path.join(app, 'build', 'install', 'app', 'lib');
  assert.deepEqual(maven.detect(app), [lib]);
  const lock = maven.readLock(app);
  assert.equal(lock.format, 'gradle-verification-metadata');
  assert.ok(lock.pinned.get('greeter-1.0.jar').has(sha256(fs.readFileSync(path.join(artifact, 'greeter-1.0.jar')))));
  const scan = await maven.scan(lib);
  assert.deepEqual(scan.packages.map(item => item.name).sort(), ['app.jar', 'com.example:greeter']);
  // The application's own jar is build output, verified by reproducing the build.
  const result = await maven.compare({
    scan, lock, store: new ReferenceStore({urls: {maven: 'http://127.0.0.1:9'}}), covered: file => file === 'app.jar',
  });
  assert.equal(result.passed, true, JSON.stringify(result));
  assert.equal(result.summary.verified, 1);
  assert.deepEqual(result.issues, []);
});
