'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const fs = require('node:fs');
const path = require('node:path');
const crypto = require('node:crypto');
const zlib = require('node:zlib');
const {execFileSync} = require('node:child_process');
const rubygems = require('../lib/ecosystems/rubygems');
const {ReferenceStore, NoLockfileError} = require('../lib/ecosystems/common');
const {
  tempDir, writeFiles, needsPosix, PATH_MAX, startServer, makeTarGz, which,
} = require('./helpers');

const hex = content => crypto.createHash('sha256').update(content).digest('hex');
const {parseGemspec, GemspecError} = rubygems;

// ─── fixtures ──────────────────────────────────────────────────────────

const metadataYaml = ({name, version, platform = 'ruby', bindir = 'bin', executables = [], extensions = []}) => `--- !ruby/object:Gem::Specification
name: ${name}
version: !ruby/object:Gem::Version
  version: '${version}'
platform: ${platform}
authors:
- Test
bindir: ${bindir}
executables: ${JSON.stringify(executables)}
extensions: ${JSON.stringify(extensions)}
require_paths:
- lib
required_ruby_version: !ruby/object:Gem::Requirement
  requirements:
  - - ">="
    - !ruby/object:Gem::Version
      version: '0'
`;

/**
 * A .gem file (a plain tar holding metadata.gz and data.tar.gz), made
 * with the system tar.
 */
function makeGem(t, {files, ...metadata}) {
  const data = makeTarGz(t, files);
  return zlib.gunzipSync(makeTarGz(t, {'metadata.gz': zlib.gzipSync(metadataYaml(metadata)), 'data.tar.gz': data}));
}

/**
 * The specification RubyGems writes when it installs a gem.
 */
const installedSpec = ({name, version, platform, bindir, executables, extensions}) => [
  '# -*- encoding: utf-8 -*-',
  `# stub: ${name} ${version} ${platform || 'ruby'} lib`,
  '',
  'Gem::Specification.new do |s|',
  `  s.name = "${name}".freeze`,
  `  s.version = "${version}".freeze`,
  ...(platform ? [`  s.platform = "${platform}".freeze`] : []),
  '',
  '  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=',
  '  s.require_paths = ["lib".freeze]',
  ...(bindir ? [`  s.bindir = "${bindir}".freeze`] : []),
  ...(executables ? [`  s.executables = [${executables.map(item => `"${item}".freeze`).join(', ')}]`] : []),
  ...(extensions ? [`  s.extensions = [${extensions.map(item => `"${item}".freeze`).join(', ')}]`] : []),
  '  s.summary = "Test".freeze',
  'end',
  '',
].join('\n');

const binstub = (gem, executable, shebang = '#!/usr/bin/env ruby') => `${shebang}
#
# This file was generated by RubyGems.
#
# The application '${gem}' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

Gem.use_gemdeps

version = ">= 0.a"

str = ARGV.first
if str
  str = str.b[/\\A_(.*)_\\z/, 1]
  if str and Gem::Version.correct?(str)
    version = str
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('${gem}', '${executable}', version)
else
gem "${gem}", version
load Gem.bin_path("${gem}", "${executable}", version)
end
`;

// RubyGems 3.7 and later (Ruby 3.5 and 4.0) end the wrapper with
// activate_and_load_bin_path.
const binstubV37 = (gem, executable) => binstub(gem, executable).replace(/^if Gem\.respond_to[\s\S]*/m, `if Gem.respond_to?(:activate_and_load_bin_path)
  Gem.activate_and_load_bin_path('${gem}', '${executable}', version)
else
  load Gem.activate_bin_path('${gem}', '${executable}', version)
end
`);

// RubyGems 2.x wrote the version check differently.
const binstubV2 = (gem, executable) => `#!/usr/bin/ruby2.5
#
# This file was generated by RubyGems.
#
# The application '${gem}' is installed as part of a gem, and
# this file is here to facilitate running it.
#

require 'rubygems'

version = ">= 0"

if ARGV.first
  str = ARGV.first
  str = str.dup.force_encoding("BINARY")
  if str =~ /\\A_(.*)_\\z/ and Gem::Version.correct?($1) then
    version = $1
    ARGV.shift
  end
end

if Gem.respond_to?(:activate_bin_path)
load Gem.activate_bin_path('${gem}', '${executable}', version)
else
gem "${gem}", version
load Gem.bin_path("${gem}", "${executable}", version)
end
`;

async function startRegistry(t) {
  const server = await startServer(t);
  return {
    server,
    store: () => new ReferenceStore({urls: {rubygems: server.url}, httpOptions: {maxRetries: 0}}),
    addGem(full, buffer) {
      server.routes[`/gems/${full}.gem`] = {body: buffer};
    },
    setVersions(name, versions) {
      server.routes[`/api/v1/versions/${name}.json`] = {body: JSON.stringify(versions), headers: {'content-type': 'application/json'}};
    },
  };
}

const issue = (result, pattern) => result.issues.find(item => pattern.test(item.message));
const finding = (result, full) => result.findings.find(item => item.path === `gems/${full}`);

// ─── specifications ────────────────────────────────────────────────────

test('parseGemspec reads the literal values of a generated specification', () => {
  const spec = parseGemspec(`# -*- encoding: utf-8 -*-
# stub: demo 1.2.3 x86_64-linux lib

Gem::Specification.new do |s|
  s.name = "demo".freeze
  s.version = "1.2.3"
  s.platform = "x86_64-linux".freeze

  s.required_rubygems_version = Gem::Requirement.new(">= 0".freeze) if s.respond_to? :required_rubygems_version=
  s.metadata = { "homepage_uri" => "https://example.test", "rubygems_mfa_required" => "true" } if s.respond_to? :metadata=
  s.require_paths = ["lib".freeze, "ext".freeze]
  s.authors = ["A \\"quoted\\" name\\n\\t\\r\\e\\s\\0\\\\\\#{x}".freeze, %q<a <nested> \\> \\\\ value>.freeze, "\\u00e9\\u{1F600}"]
  s.bindir = "exe".freeze
  s.date = Time.utc(2024, 1, 2)
  s.executables = ["demo".freeze]
  s.extensions = []
  s.specification_version = 4
  s.required_ruby_version = Gem::Requirement.new([">= 2.7".freeze, "< 4".freeze])
  s.original_platform = Gem::Platform.new(["x86_64".freeze, "linux".freeze, nil])
  s.rubygems_version = Gem::Version.new("3.5.0").freeze.freeze
  s.has_rdoc = true
  s.autorequire = false
  s.signing_key = nil
  s.cert_chain = [
    "a",
    "b"
  ]
  s.post_install_message = {
    "note" => -1.5, 2 => nil,
  }

  if s.respond_to? :specification_version then
    s.specification_version = 4
  end

  if s.respond_to?(:add_runtime_dependency) then
    s.add_runtime_dependency(%q<json>.freeze, [">= 2".freeze, "< 3".freeze])
    s.add_development_dependency %q<rake>.freeze, ["~> 13"]
  else
    s.add_dependency %q<json>.freeze
  end
end
`);
  assert.deepEqual(spec, {
    name: 'demo',
    version: '1.2.3',
    platform: 'x86_64-linux',
    // eslint-disable-next-line camelcase -- a gemspec attribute
    require_paths: ['lib', 'ext'],
    bindir: 'exe',
    executables: ['demo'],
    extensions: [],
    dependencies: [['json', ['>= 2', '< 3']], ['rake', ['~> 13']], ['json']],
  });
  const authors = parseGemspec('Gem::Specification.new do |s|\n  s.authors = ["A \\"quoted\\" name\\n\\t\\r\\e\\s\\0\\\\\\#{x}", %q<a <nested> \\> \\\\ value>, "\\u00e9\\u{1F600}"]\nend\n');
  assert.equal(authors.name, null);

  // Defaults for what the specification leaves out.
  assert.deepEqual(parseGemspec('\n\nGem::Specification.new do |s|\n  s.name = nil\n  s.version = 1\nend\n\n'), {
    // eslint-disable-next-line camelcase -- a gemspec attribute
    name: null, version: null, platform: 'ruby', require_paths: ['lib'], bindir: 'bin', executables: [], extensions: [], dependencies: [],
  });
});

test('parseGemspec rejects anything that could run code', () => {
  const wrap = body => `Gem::Specification.new do |s|\n${body}\nend\n`;
  const rejects = {
    unterminated: [wrap('  s.name = "demo'), /unterminated string/],
    interpolation: [wrap('  s.name = "#{`id`}"'), /interpolation in a string/],
    instanceInterpolation: [wrap('  s.name = "#@x"'), /interpolation/],
    unicode: [wrap(String.raw`  s.name = "\uZZZZ"`), /invalid unicode escape/],
    escape: [wrap(String.raw`  s.name = "\x41"`), /unsupported escape \\x/],
    percent: [wrap('  s.name = %q<demo'), /unterminated %q string/],
    backtick: [wrap('  s.name = `id`'), /unexpected "`"/],
    minus: [wrap('  s.name = -x'), /unexpected "-"/],
    call: [wrap('  s.name = File.read("/etc/passwd")'), /unexpected {"type":"word","value":"File"}/],
    system: [wrap('  system("id")'), /expected s, found/],
    method: [wrap('  s.instance_eval("x")'), /unexpected s\.instance_eval/],
    reader: [wrap('  s.name'), /unexpected s\.name/],
    gemConstant: [wrap('  s.version = Gem::Deferred.new("1")'), /unexpected Gem::Deferred/],
    constructor: [wrap('  s.version = Gem::Version.load("1")'), /expected new/],
    chained: [wrap('  s.name = "demo".upcase'), /unexpected {"type":"punct","value":"\."} after s\.name/],
    semicolon: [wrap('  s.name = "demo"; system("id")'), /unexpected ";"/],
    trailing: [wrap('  s.name = "demo" "x"'), /after s\.name/],
    after: [`${wrap('  s.name = "demo"')}system("id")\n`, /content after the specification/],
    truncated: ['Gem::Specification.new do |s|\n  s.name = "demo"', /expected s, found undefined/],
    header: ['Gem::Specification.new { |s| }', /expected do/],
    condition: [wrap('  if true\n  end'), /expected s, found/],
    hashKey: [wrap('  s.metadata = { "a" : 1 }'), /unexpected ":"|expected =>/],
    arguments: ['Gem::Specification.new do |s|\n  s.add_dependency("a"', /unexpected undefined/],
    symbol: [wrap('  s.metadata = { :key => "x" }'), /unexpected {"type":"symbol","value":"key"}/],
    hashAtEnd: [wrap('  s.name = "demo#').trimEnd().replace(/\nend$/, ''), /unterminated string/],
    backslashAtEnd: ['Gem::Specification.new do |s|\n  s.name = %q<demo\\', /unterminated %q string/],
    minusAtEnd: ['Gem::Specification.new do |s|\n  s.name = -', /unexpected "-"/],
    colonAtEnd: ['Gem::Specification.new do |s|\n  s.name = :', /unexpected ":"/],
    attribute: [wrap('  s.[0] = 1'), /expected word, found {"type":"punct","value":"\["}/],
    conditionSymbol: [wrap('  if s.respond_to? "name="\n  end'), /expected symbol, found {"type":"string"/],
  };
  for (const [label, [text, pattern]] of Object.entries(rejects)) {
    assert.throws(() => parseGemspec(text), error => error instanceof GemspecError && pattern.test(error.message), label);
  }
});

test('binstubTarget recognizes the wrappers RubyGems generates', () => {
  assert.deepEqual(rubygems.binstubTarget(binstub('demo', 'demo-cli')), {gem: 'demo', executable: 'demo-cli'});
  assert.deepEqual(rubygems.binstubTarget(binstubV2('rake', 'rake')), {gem: 'rake', executable: 'rake'});
  assert.deepEqual(rubygems.binstubTarget(binstubV37('demo', 'demo-cli')), {gem: 'demo', executable: 'demo-cli'});
  assert.equal(rubygems.binstubTarget(binstubV37('demo', 'demo').replace('bin_path(\'demo\'', 'bin_path(\'other\'')), null);
  assert.equal(rubygems.binstubTarget(binstubV37('demo', 'demo').replace('else\n', 'else\n  system("id")\n')), null);
  assert.deepEqual(rubygems.binstubTarget(binstub('demo', 'demo').replace('Gem.use_gemdeps\n\n', '')), {gem: 'demo', executable: 'demo'});
  assert.equal(rubygems.binstubTarget(binstub('demo', 'demo').replace('require \'rubygems\'', 'require \'rubygems\'\nsystem("id")')), null);
  assert.equal(rubygems.binstubTarget(`${binstub('demo', 'demo')}\nsystem("id")\n`), null);
  assert.equal(rubygems.binstubTarget(binstub('demo', 'demo').replace('gem "demo"', 'gem "other"')), null);
  assert.equal(rubygems.binstubTarget('#!/bin/sh\nexec ruby "$@"\n'), null);
});

// ─── lockfile and metadata ─────────────────────────────────────────────

const LOCKFILE = `GIT
  remote: https://github.com/example/gitgem.git
  revision: ${'a'.repeat(40)}
  specs:
    gitgem (0.1.0)

PATH
  remote: .
  specs:
    local (1.0.0)

GEM
  remote: https://rubygems.org/
  specs:
    demo (1.0.0)
      json (>= 2)
    nokogiri (1.16.0-x86_64-linux)
      racc (~> 1.4)
    racc (1.7.3)

PLATFORMS
  ruby
  x86_64-linux

DEPENDENCIES
  demo
  gitgem!

CHECKSUMS
  demo (1.0.0) sha256=${'b'.repeat(64)}
  nokogiri (1.16.0-x86_64-linux) sha256=${'c'.repeat(64)}
  racc (1.7.3)

BUNDLED WITH
   2.6.0
`;

test('parseGemfileLock reads gem, git and path sources and checksums', () => {
  const {gems, checksums} = rubygems.parseGemfileLock(LOCKFILE.replaceAll('\n', '\r\n'));
  assert.deepEqual([...gems.keys()], ['gitgem-0.1.0', 'local-1.0.0', 'demo-1.0.0', 'nokogiri-1.16.0-x86_64-linux', 'racc-1.7.3']);
  assert.deepEqual(gems.get('gitgem-0.1.0').source, {type: 'git', remote: 'https://github.com/example/gitgem.git', revision: 'a'.repeat(40)});
  assert.deepEqual(gems.get('local-1.0.0').source, {type: 'path', remote: '.'});
  assert.deepEqual(gems.get('nokogiri-1.16.0-x86_64-linux'), {
    name: 'nokogiri', version: '1.16.0', platform: 'x86_64-linux', full: 'nokogiri-1.16.0-x86_64-linux', source: {type: 'gem', remote: 'https://rubygems.org/'},
  });
  assert.equal(gems.get('demo-1.0.0').platform, 'ruby');
  assert.deepEqual([...checksums], [['demo-1.0.0', 'b'.repeat(64)], ['nokogiri-1.16.0-x86_64-linux', 'c'.repeat(64)]]);
});

test('readLock finds Gemfile.lock or gems.locked', t => {
  const dir = tempDir(t);
  assert.throws(() => rubygems.readLock(dir), error => error instanceof NoLockfileError && /Gemfile\.lock, gems\.locked/.test(error.message));
  writeFiles(dir, {'gems.locked': LOCKFILE, 'sub/Other.lock': 'GEM\n  specs:\n    x (1)\n'});
  const lock = rubygems.readLock(dir);
  assert.equal(lock.format, 'bundler');
  assert.equal(lock.file, 'gems.locked');
  assert.equal(lock.gems.size, 5);
  assert.deepEqual([...rubygems.readLock(dir, {lockfile: 'sub/Other.lock'}).gems.keys()], ['x-1']);
  assert.throws(() => rubygems.readLock(dir, {lockfile: 'nope.lock'}), /No Ruby lockfile found \(nope\.lock\)/);
  assert.equal(rubygems.name, 'rubygems');
  assert.deepEqual(rubygems.lockfiles, ['Gemfile.lock', 'gems.locked']);
});

test('parseGemMetadata reads gem metadata without Ruby object tags', () => {
  assert.deepEqual(rubygems.parseGemMetadata(metadataYaml({
    name: 'demo', version: '1.0.0', bindir: 'exe', executables: ['demo'], extensions: ['ext/extconf.rb'],
  })), {
    // eslint-disable-next-line camelcase -- a gemspec attribute
    name: 'demo', version: '1.0.0', platform: 'ruby', require_paths: ['lib'], bindir: 'exe', executables: ['demo'], extensions: ['ext/extconf.rb'],
  });
  const platform = rubygems.parseGemMetadata('name: demo\nversion: \'2.0\'\nplatform: !ruby/object:Gem::Platform\n  cpu: x86_64\n  os: linux\nfiles: !binary |-\n  ZGVtbw==\n');
  assert.equal(platform.version, '2.0');
  assert.equal(platform.platform, 'ruby');
  const empty = rubygems.parseGemMetadata('');
  assert.equal(empty.name, undefined);
  assert.deepEqual([empty.platform, empty.require_paths, empty.bindir, empty.executables, empty.extensions], ['ruby', ['lib'], 'bin', [], []]);
});

test('readGem hashes a gem\'s data and reads its metadata', t => {
  const gem = makeGem(t, {name: 'demo', version: '1.0.0', files: {'lib/demo.rb': 'module Demo; end\n'}});
  const {files, metadata} = rubygems.readGem(gem);
  assert.deepEqual(files, {'lib/demo.rb': hex('module Demo; end\n')});
  assert.equal(metadata.name, 'demo');
  // Old tar writers mark regular files with a NUL type flag.
  const old = Buffer.from(gem);
  for (let offset = 0; offset + 512 <= old.length && old[offset] !== 0;) {
    const size = Number.parseInt(old.subarray(offset + 124, offset + 136).toString().replaceAll('\0', '').trim(), 8);
    old[offset + 156] = 0;
    old.fill(0x20, offset + 148, offset + 156);
    let sum = 0;
    for (let index = offset; index < offset + 512; index++) {
      sum += old[index];
    }

    old.write(`${sum.toString(8).padStart(6, '0')}\0 `, offset + 148, 'latin1');
    offset += 512 + (Math.ceil(size / 512) * 512);
  }

  assert.deepEqual(rubygems.readGem(old).files, files);
  const notGem = zlib.gunzipSync(makeTarGz(t, {'metadata.gz': zlib.gzipSync('name: x\n')}));
  assert.throws(() => rubygems.readGem(notGem), /Not a gem file/);
});

// ─── attester ──────────────────────────────────────────────────────────

test('detect finds Bundler install directories', t => {
  const root = tempDir(t);
  writeFiles(root, {
    'vendor/bundle/ruby/3.3.0/specifications/.keep': '',
    'vendor/bundle/ruby/3.2.0/gems/.keep': '',
    'vendor/bundle/ruby/current/specifications/.keep': '',
    '.bundle/ruby/3.1.0/specifications/.keep': '',
  });
  assert.deepEqual(rubygems.detect(root), [path.join(root, 'vendor/bundle/ruby/3.3.0'), path.join(root, '.bundle/ruby/3.1.0')]);
  assert.deepEqual(rubygems.detect(path.join(root, 'nowhere')), []);
  assert.equal(rubygems.installRoot('/srv/app/vendor/bundle/ruby/3.3.0'), '/srv/app/vendor/bundle/ruby/3.3.0');
});

test('scan hashes gems, specifications, extensions, bin/ and plugins', {skip: needsPosix}, async t => {
  const home = tempDir(t);
  writeFiles(home, {
    'gems/demo-1.0.0/lib/demo.rb': 'module Demo; end\n',
    'gems/demo-1.0.0/exe/demo': 'puts 1\n',
    'specifications/demo-1.0.0.gemspec': installedSpec({
      name: 'demo', version: '1.0.0', executables: ['demo'], bindir: 'exe',
    }),
    'gems/nospec-2.0.0-x86_64-linux/lib/x.rb': '',
    'gems/weird/lib/x.rb': '',
    'gems/badspec-1.0/lib/x.rb': '',
    'specifications/badspec-1.0.gemspec': 'system("id")\n',
    'gems/bigspec-1.0/lib/x.rb': '',
    'specifications/bigspec-1.0.gemspec': `# ${'x'.repeat(300 * 1024)}\n`,
    'gems/dirspec-1.0/lib/x.rb': '',
    'specifications/dirspec-1.0.gemspec/.keep': '',
    'gems/native-0.1.0/lib/native.rb': '',
    'specifications/native-0.1.0.gemspec': installedSpec({name: 'native', version: '0.1.0', extensions: ['ext/extconf.rb']}),
    'extensions/x86_64-linux/3.3.0/native-0.1.0/native.so': 'ELF',
    'extensions/x86_64-linux/3.3.0/orphan-1.0/orphan.so': 'ELF',
    'specifications/orphan-1.0.gemspec': installedSpec({name: 'orphan', version: '1.0'}),
    'gems/not-a-directory': '',
    'bin/demo': binstub('demo', 'demo'),
    'bin/big': 'x'.repeat(70 * 1024),
    'bin/subdir/.keep': '',
    'plugins/demo_plugin.rb': 'require "x"\n',
  });
  fs.symlinkSync('../lib/demo.rb', path.join(home, 'gems/demo-1.0.0/exe/link'));
  const result = await rubygems.scan(home);
  const byPath = Object.fromEntries(result.packages.map(item => [item.path, item]));
  assert.deepEqual(Object.keys(byPath), ['gems/badspec-1.0', 'gems/bigspec-1.0', 'gems/demo-1.0.0', 'gems/dirspec-1.0', 'gems/native-0.1.0', 'gems/nospec-2.0.0-x86_64-linux', 'gems/weird']);
  const demo = byPath['gems/demo-1.0.0'];
  assert.equal(demo.name, 'demo');
  assert.equal(demo.version, '1.0.0');
  assert.deepEqual(demo.files, {'exe/demo': hex('puts 1\n'), 'exe/link': 'symlink:../lib/demo.rb', 'lib/demo.rb': hex('module Demo; end\n')});
  assert.match(demo.meta.gemspec, /s\.name = "demo"/);
  assert.equal(demo.meta.extension, undefined);
  assert.deepEqual([byPath['gems/nospec-2.0.0-x86_64-linux'].name, byPath['gems/nospec-2.0.0-x86_64-linux'].version], ['nospec', '2.0.0']);
  assert.deepEqual([byPath['gems/weird'].name, byPath['gems/weird'].version], ['weird', null]);
  assert.deepEqual([byPath['gems/badspec-1.0'].name, byPath['gems/badspec-1.0'].meta.gemspec], ['badspec', 'system("id")\n']);
  assert.equal(byPath['gems/bigspec-1.0'].meta.gemspec, null);
  assert.deepEqual(byPath['gems/native-0.1.0'].meta.extension, {'native.so': hex('ELF')});
  assert.equal(byPath['gems/native-0.1.0'].meta.extensionPath, 'extensions/x86_64-linux/3.3.0/native-0.1.0');
  assert.deepEqual(result.unaccounted, ['extensions/x86_64-linux/3.3.0/orphan-1.0/', 'specifications/orphan-1.0.gemspec']);
  assert.deepEqual(result.errors, [{path: 'specifications/dirspec-1.0.gemspec', error: 'EISDIR'}, {path: 'bin/subdir', error: 'EISDIR'}]);
  assert.equal(result.meta.bin.demo, binstub('demo', 'demo'));
  assert.equal(result.meta.bin.big, null);
  assert.deepEqual(result.meta.plugins, {'demo_plugin.rb': 'require "x"\n'});
});

test('scan reports a missing gem directory and unreadable directories', {skip: !(PATH_MAX && which('bash')) && 'needs a path length limit and bash'}, async t => {
  const home = tempDir(t);
  const empty = await rubygems.scan(home);
  assert.deepEqual(empty.errors, [{path: 'gems', error: 'ENOENT'}]);
  assert.deepEqual(empty.packages, []);
  assert.deepEqual(empty.meta, {bin: {}, plugins: {}});

  // A directory deeper than PATH_MAX cannot be listed by its absolute path.
  const gem = path.join(home, 'gems/deep-1.0');
  writeFiles(gem, {'lib/deep.rb': ''});
  execFileSync('bash', ['-c', 'cd "$1" && for i in $(seq 20); do d=$(printf "%0250d" "$i"); mkdir "$d" && cd "$d"; done', 'bash', gem]);
  let result;
  try {
    result = await rubygems.scan(home);
  } finally {
    execFileSync('rm', ['-rf', path.join(gem, '0'.repeat(249) + '1')]);
  }

  assert.ok(result.errors.some(error => error.path.startsWith('gems/deep-1.0/') && error.error === 'ENAMETOOLONG'), JSON.stringify(result.errors));
});

// ─── verifier ──────────────────────────────────────────────────────────

/**
 * An installed gem exactly as RubyGems unpacks it.
 */
function installedGem(t, metadata, files, extra = {}) {
  const gem = makeGem(t, {...metadata, files});
  const full = metadata.platform ? `${metadata.name}-${metadata.version}-${metadata.platform}` : `${metadata.name}-${metadata.version}`;
  return {
    gem,
    full,
    item: {
      name: metadata.name,
      version: metadata.version,
      path: `gems/${full}`,
      files: Object.fromEntries(Object.entries(files).map(([file, content]) => [file, hex(content)])),
      meta: {full, gemspec: installedSpec(metadata), ...extra},
    },
  };
}

const lockOf = (entries, checksums = {}) => ({
  gems: new Map(entries.map(entry => [entry.full, {platform: 'ruby', source: {type: 'gem', remote: 'https://rubygems.org/'}, ...entry}])),
  checksums: new Map(Object.entries(checksums)),
});

const scanOf = (packages, meta, unaccounted = []) => ({
  packages, unaccounted, meta: meta || {bin: {}, plugins: {}}, links: [], caches: [], errors: [],
});

test('compare verifies gems against the checksums Gemfile.lock pins', async t => {
  const registry = await startRegistry(t);
  const demo = installedGem(t, {
    name: 'demo', version: '1.0.0', bindir: 'exe', executables: ['demo'],
  }, {'lib/demo.rb': 'module Demo; end\n', 'exe/demo': 'puts 1\n'});
  const native = installedGem(t, {
    name: 'native', version: '0.1.0', platform: 'x86_64-linux', extensions: ['ext/extconf.rb'],
  }, {'lib/native.rb': '', 'ext/extconf.rb': ''}, {extension: {'native.so': hex('ELF')}, extensionPath: 'extensions/x86_64-linux/3.3.0/native-0.1.0-x86_64-linux'});
  native.item.files['lib/native.so'] = hex('ELF');
  const bare = installedGem(t, {name: 'bare', version: '1.0', extensions: ['ext/extconf.rb']}, {'ext/extconf.rb': ''});
  for (const gem of [demo, native, bare]) {
    registry.addGem(gem.full, gem.gem);
  }

  const lock = lockOf([
    {name: 'demo', version: '1.0.0', full: demo.full},
    {
      name: 'native', version: '0.1.0', platform: 'x86_64-linux', full: native.full,
    },
    {name: 'bare', version: '1.0', full: bare.full},
  ], {[demo.full]: hex(demo.gem), [native.full]: hex(native.gem), [bare.full]: hex(bare.gem)});
  const result = await rubygems.compare({
    scan: scanOf([demo.item, native.item, bare.item], {bin: {demo: binstub('demo', 'demo')}, plugins: {}}),
    lock,
    store: registry.store(),
  });
  assert.equal(result.passed, true, JSON.stringify(result));
  assert.equal(result.summary.verified, 1);
  assert.equal(result.summary.built, 2);
  assert.deepEqual(result.issues, [{
    severity: 'warn',
    message: 'Gems with native extensions were compiled on the server; their unchanged sources match, but the compiled output cannot be compared with anything',
    items: ['bare-1.0 (0 files in no extensions directory)', 'native-0.1.0-x86_64-linux (1 files in extensions/x86_64-linux/3.3.0/native-0.1.0-x86_64-linux)'],
  }]);
});

test('a FIFO in an installed gem (which require would read) makes the package check fail', {skip: process.platform !== 'linux'}, async t => {
  const registry = await startRegistry(t);
  const metadata = {name: 'demo', version: '1.0.0', extensions: ['ext/extconf.rb']};
  const files = {'lib/demo.rb': 'require "demo/util"\n', 'lib/demo/util.rb': 'module Demo; end\n', 'ext/extconf.rb': ''};
  const gem = makeGem(t, {...metadata, files});
  registry.addGem('demo-1.0.0', gem);
  const home = tempDir(t);
  writeFiles(home, {
    ...Object.fromEntries(Object.entries(files).map(([file, content]) => [`gems/demo-1.0.0/${file}`, content])),
    'specifications/demo-1.0.0.gemspec': installedSpec(metadata),
    'extensions/x86_64-linux/3.3.0/demo-1.0.0/demo.so': 'ELF',
  });
  const lock = lockOf([{name: 'demo', version: '1.0.0', full: 'demo-1.0.0'}], {'demo-1.0.0': hex(gem)});
  const check = async () => rubygems.compare({scan: await rubygems.scan(home), lock, store: registry.store()});

  const clean = await check();
  assert.equal(clean.passed, true, JSON.stringify(clean.issues));

  // `require "demo/util"` finds lib/demo/util.so before a later load path's
  // util.rb, and Ruby reads a FIFO like a file: whatever writes to it runs.
  execFileSync('mkfifo', [path.join(home, 'gems/demo-1.0.0/lib/demo/util.so'), path.join(home, 'extensions/x86_64-linux/3.3.0/demo-1.0.0/hook.so')]);
  const scan = await rubygems.scan(home);
  assert.deepEqual(scan.errors, [
    {path: 'gems/demo-1.0.0/lib/demo/util.so', error: 'ENOTFILE'},
    {path: 'extensions/x86_64-linux/3.3.0/demo-1.0.0/hook.so', error: 'ENOTFILE'},
  ]);
  const result = await check();
  assert.equal(result.passed, false);
  assert.deepEqual(issue(result, /could not read/).items, ['extensions/x86_64-linux/3.3.0/demo-1.0.0/hook.so: ENOTFILE', 'gems/demo-1.0.0/lib/demo/util.so: ENOTFILE']);
});

test('compareGemDirectory compares a gem no lockfile pins (Bundler) with the registry\'s', async t => {
  const registry = await startRegistry(t);
  const files = {'lib/bundler.rb': 'module Bundler; end\n', 'lib/bundler/setup.rb': 'require "bundler"\n', 'exe/bundle': '#!/usr/bin/env ruby\n'};
  const gem = makeGem(t, {name: 'bundler', version: '2.5.22', files});
  registry.addGem('bundler-2.5.22', gem);
  registry.setVersions('bundler', [{number: '2.5.22', platform: 'ruby', sha: hex(gem)}]);
  const installed = Object.fromEntries(Object.entries(files).map(([file, content]) => [file, hex(content)]));
  const store = registry.store();
  assert.deepEqual(await rubygems.compareGemDirectory({
    name: 'bundler', version: '2.5.22', files: installed, store,
  }), {modified: [], missing: [], added: []});
  assert.deepEqual(await rubygems.compareGemDirectory({
    name: 'bundler', version: '2.5.22', files: {...installed, 'lib/bundler/setup.rb': hex('evil'), 'lib/evil.rb': hex('evil')}, store,
  }), {modified: ['lib/bundler/setup.rb'], missing: [], added: ['lib/evil.rb']});
  await assert.rejects(rubygems.compareGemDirectory({
    name: 'bundler', version: '9.9.9', files: installed, store,
  }), /the registry has no checksum for bundler 9\.9\.9 \(ruby\)/);
});

test('compare reports gems that differ from their reference', async t => {
  const registry = await startRegistry(t);
  const make = (name, extra) => installedGem(t, {name, version: '1.0'}, {'lib/x.rb': 'x'}, extra);
  const gems = {
    modified: make('modified'),
    spec: make('spec'),
    literal: make('literal'),
    nospec: make('nospec'),
    extension: make('extension', {extension: {'x.so': hex('ELF')}, extensionPath: 'extensions/x/y/extension-1.0'}),
    tampered: make('tampered'),
    gone: make('gone'),
    unpinned: make('unpinned'),
    nochecksum: make('nochecksum'),
    platform: make('platform'),
    registryless: make('registryless'),
    git: make('git'),
    unlocked: make('unlocked'),
  };
  gems.modified.item.files['lib/x.rb'] = hex('y');
  gems.modified.item.files['lib/added.rb'] = hex('z');
  gems.spec.item.meta.gemspec = installedSpec({
    name: 'spec', version: '1.0', bindir: 'exe', executables: ['spec'],
  });
  gems.literal.item.meta.gemspec = 'Gem::Specification.new do |s|\n  s.name = "literal"\n  system("id")\nend\n';
  delete gems.nospec.item.meta.gemspec;
  for (const gem of Object.values(gems)) {
    registry.addGem(gem.full, gem.gem);
  }

  delete registry.server.routes[`/gems/${gems.gone.full}.gem`];
  registry.setVersions('unpinned', [{number: '0.9', sha: 'f'.repeat(64)}, {number: '1.0', platform: 'ruby', sha: hex(gems.unpinned.gem)}]);
  registry.setVersions('nochecksum', [{number: '1.0'}]);
  registry.setVersions('platform', [{number: '1.0', platform: 'java', sha: hex(gems.platform.gem)}]);
  const checksums = Object.fromEntries(Object.values(gems).map(gem => [gem.full, hex(gem.gem)]));
  checksums[gems.tampered.full] = 'e'.repeat(64);
  delete checksums[gems.unpinned.full];
  delete checksums[gems.nochecksum.full];
  delete checksums[gems.platform.full];
  delete checksums[gems.registryless.full];
  const entries = Object.entries(gems).filter(([key]) => key !== 'unlocked').map(([name, gem]) => ({name, version: '1.0', full: gem.full}));
  const lock = lockOf(entries, checksums);
  lock.gems.get('git-1.0').source = {type: 'git', remote: 'https://github.com/example/git.git', revision: 'a'.repeat(40)};

  const result = await rubygems.compare({scan: scanOf(Object.values(gems).map(gem => gem.item)), lock, store: registry.store()});
  const reasons = Object.fromEntries(result.findings.map(item => [item.package, `${item.status}: ${item.reason}`]));
  assert.deepEqual(reasons, {
    'modified@1.0': 'failed: files differ from the gem',
    'spec@1.0': 'failed: its specification differs from the gem\'s metadata (bindir, executables)',
    'literal@1.0': 'failed: its specification is not a generated literal specification: expected s, found {"type":"word","value":"system"}',
    'nospec@1.0': 'failed: its specification is not a generated literal specification: expected Gem, found undefined',
    'extension@1.0': 'failed: compiled extension files for a gem that has no extensions (extensions/x/y/extension-1.0)',
    'tampered@1.0': 'failed: Downloaded tampered-1.0.gem does not match its checksum',
    'gone@1.0': `error: HTTP 404 fetching ${registry.server.url}/gems/gone-1.0.gem`,
    'nochecksum@1.0': 'error: the registry has no checksum for nochecksum 1.0 (ruby)',
    'platform@1.0': 'error: the registry has no checksum for platform 1.0 (ruby)',
    'registryless@1.0': `error: HTTP 404 fetching ${registry.server.url}/api/v1/versions/registryless.json`,
    'git@1.0': 'unverifiable: installed from git (https://github.com/example/git.git); only gems from a gem server are compared',
    'unlocked@1.0': 'failed: installed gem is not in the lockfile',
  });
  assert.deepEqual(finding(result, 'modified-1.0').modified, ['lib/x.rb']);
  assert.deepEqual(finding(result, 'modified-1.0').added, ['lib/added.rb']);
  assert.equal(result.summary.verified, 1);
  assert.deepEqual(issue(result, /no checksums/).items, ['unpinned-1.0']);
  assert.equal(issue(result, /no checksums/).message, 'Gemfile.lock has no checksums for these gems; they were compared with the registry\'s checksum instead (Bundler 2.6 and later write them: `bundle lock --add-checksums`)');

  const unlocked = await rubygems.compare({scan: scanOf([gems.unlocked.item]), lock: null, store: registry.store()});
  assert.equal(unlocked.findings[0].reason, 'no lockfile pins this gem');
});

test('compare checks bin/ wrappers, plugins and orphaned specifications', async t => {
  const registry = await startRegistry(t);
  const demo = installedGem(t, {
    name: 'demo', version: '1.0', bindir: 'exe', executables: ['demo', 'demo-admin'],
  }, {'exe/demo': '', 'exe/demo-admin': ''});
  const other = installedGem(t, {name: 'other', version: '1.0'}, {'lib/other.rb': ''});
  other.item.files['lib/other.rb'] = hex('changed');
  registry.addGem(demo.full, demo.gem);
  registry.addGem(other.full, other.gem);
  const lock = lockOf([{name: 'demo', version: '1.0', full: demo.full}, {name: 'other', version: '1.0', full: other.full}], {[demo.full]: hex(demo.gem), [other.full]: hex(other.gem)});
  const result = await rubygems.compare({
    scan: scanOf([demo.item, other.item], {
      bin: {
        demo: binstub('demo', 'demo'),
        'demo-admin': binstubV2('demo', 'demo-admin'),
        renamed: binstub('demo', 'demo'),
        imposter: binstub('other', 'demo'),
        otherbin: binstub('other', 'otherbin'),
        huge: null,
        script: '#!/bin/sh\n',
      },
      plugins: {'demo_plugin.rb': 'require "x"\n'},
    }, ['specifications/orphan-1.0.gemspec']),
    lock,
    store: registry.store(),
  });
  assert.equal(result.passed, false);
  assert.deepEqual(result.issues.map(item => [item.severity, item.items]), [
    ['fail', ['bin/huge', 'bin/imposter', 'bin/otherbin', 'bin/renamed', 'bin/script']],
    ['fail', ['plugins/demo_plugin.rb']],
    ['fail', ['specifications/orphan-1.0.gemspec']],
  ]);

  // A scan without bin/ or plugins metadata.
  const minimal = await rubygems.compare({scan: scanOf([demo.item], {}), lock, store: registry.store()});
  assert.equal(minimal.passed, true);
});

// ─── real bundles ──────────────────────────────────────────────────────

const hasRuby = which('ruby') && which('gem') && which('bundle');

function run(command, args, options) {
  const env = {
    ...process.env, BUNDLE_USER_HOME: path.join(options.cwd, '.bundle-home'), BUNDLE_GEMFILE: path.join(options.cwd, 'Gemfile'), ...options.env,
  };
  delete env.GEM_HOME;
  delete env.BUNDLE_PATH;
  return execFileSync(command, args, {
    stdio: 'pipe', encoding: 'utf8', ...options, env,
  });
}

/**
 * Build a gem from a gemspec and files with `gem build`.
 */
function buildGem(t, name, gemspec, files) {
  const source = tempDir(t, `attestium-gem-${name}-`);
  writeFiles(source, {...files, [`${name}.gemspec`]: gemspec});
  run('gem', ['build', '--silent', `${name}.gemspec`], {cwd: source, env: {SOURCE_DATE_EPOCH: '1700000000'}});
  const file = fs.readdirSync(source).find(entry => entry.endsWith('.gem'));
  return {full: file.replace(/\.gem$/, ''), buffer: fs.readFileSync(path.join(source, file))};
}

const gemspecOf = (name, body) => `Gem::Specification.new do |s|
  s.name = "${name}"
  s.version = "1.0.0"
  s.summary = "Test gem"
  s.authors = ["Test"]
  s.license = "MIT"
${body}
end
`;

test('a Bundler install from local gems verifies against Gemfile.lock', {skip: !hasRuby && 'ruby, gem and bundle are not installed'}, async t => {
  const demo = buildGem(t, 'attestium-demo', gemspecOf('attestium-demo', '  s.files = ["lib/demo.rb", "exe/demo"]\n  s.bindir = "exe"\n  s.executables = ["demo"]'), {
    'lib/demo.rb': 'module Demo; end\n', 'exe/demo': '#!/usr/bin/env ruby\nrequire "demo"\n',
  });
  const gems = [demo];
  const hasCompiler = which('make') && (which('cc') || which('gcc'));
  if (hasCompiler) {
    gems.push(buildGem(t, 'attestium-native', gemspecOf('attestium-native', '  s.files = ["lib/native.rb", "ext/native/extconf.rb", "ext/native/native.c"]\n  s.extensions = ["ext/native/extconf.rb"]'), {
      'lib/native.rb': 'require "native/native"\n',
      'ext/native/extconf.rb': 'require "mkmf"\ncreate_makefile("native/native")\n',
      'ext/native/native.c': '#include <ruby.h>\nvoid Init_native(void) {}\n',
    }));
  }

  const app = tempDir(t);
  writeFiles(app, {
    Gemfile: `source "https://rubygems.org"\n${gems.map(gem => `gem "${gem.full.replace(/-1\.0\.0$/, '')}"\n`).join('')}`,
    ...Object.fromEntries(gems.map(gem => [`vendor/cache/${gem.full}.gem`, gem.buffer])),
  });
  run('bundle', ['config', 'set', '--local', 'path', 'vendor/bundle'], {cwd: app});
  run('bundle', ['install', '--local'], {cwd: app});

  const registry = await startRegistry(t);
  for (const gem of gems) {
    registry.addGem(gem.full, gem.buffer);
  }

  const [home] = rubygems.detect(app);
  assert.ok(home, 'install directory found');
  const installed = await rubygems.scan(home);
  assert.deepEqual(installed.errors, []);
  const lock = rubygems.readLock(app);
  assert.equal(lock.checksums.get(demo.full), hex(demo.buffer));
  let result = await rubygems.compare({scan: installed, lock, store: registry.store()});
  assert.deepEqual(result.findings, []);
  assert.equal(result.passed, true, JSON.stringify(result.issues));
  assert.equal(result.summary.verified, 1);
  assert.equal(result.summary.built, gems.length - 1);
  assert.equal(rubygems.binstubTarget(installed.meta.bin.demo).gem, 'attestium-demo');

  // The registry's checksum, when the lockfile has none.
  const unpinned = {...lock, checksums: new Map()};
  for (const gem of gems) {
    registry.setVersions(gem.full.replace(/-1\.0\.0$/, ''), [{number: '1.0.0', platform: 'ruby', sha: hex(gem.buffer)}]);
  }

  result = await rubygems.compare({scan: installed, lock: unpinned, store: registry.store()});
  assert.equal(result.passed, true);
  assert.deepEqual(issue(result, /no checksums/).items, gems.map(gem => gem.full).sort());

  // Tampering with a gem's code, its specification and bin/.
  fs.appendFileSync(path.join(home, 'gems', demo.full, 'lib/demo.rb'), 'system("id")\n');
  fs.writeFileSync(path.join(home, 'bin/extra'), '#!/bin/sh\n');
  result = await rubygems.compare({scan: await rubygems.scan(home), lock, store: registry.store()});
  assert.equal(result.passed, false);
  assert.deepEqual(finding(result, demo.full).modified, ['lib/demo.rb']);
  assert.deepEqual(issue(result, /Files in bin/).items, ['bin/demo', 'bin/extra']);
  const specFile = path.join(home, 'specifications', `${demo.full}.gemspec`);
  fs.writeFileSync(specFile, fs.readFileSync(specFile, 'utf8').replace('s.name = "attestium-demo".freeze', 's.name = "attestium-demo".freeze\n  s.files = Dir["**/*"]'));
  result = await rubygems.compare({scan: await rubygems.scan(home), lock, store: registry.store()});
  assert.match(finding(result, demo.full).reason, /not a generated literal specification/);
});

test('specifications RubyGems installed on this machine parse as literals', {skip: !hasRuby && 'ruby is not installed'}, t => {
  const gemDir = execFileSync('gem', ['env', 'gemdir'], {encoding: 'utf8'}).trim();
  const directories = [path.join(gemDir, 'specifications'), path.join(gemDir, 'specifications/default')];
  const files = directories.flatMap(directory => {
    try {
      return fs.readdirSync(directory).filter(name => name.endsWith('.gemspec')).map(name => path.join(directory, name));
    } catch {
      return [];
    }
  });
  if (files.length === 0) {
    t.skip('no installed specifications');
    return;
  }

  for (const file of files) {
    const spec = parseGemspec(fs.readFileSync(file, 'utf8'));
    assert.ok(path.basename(file).startsWith(`${spec.name}-${spec.version}`), file);
  }
});

test('a gem with native extensions may gain build output, not Ruby source', async t => {
  const registry = await startRegistry(t);
  const native = installedGem(t, {name: 'native', version: '0.1.0', extensions: ['ext/extconf.rb']}, {'lib/native.rb': '', 'ext/extconf.rb': ''});
  registry.addGem(native.full, native.gem);
  const lock = lockOf([{name: 'native', version: '0.1.0', full: native.full}], {[native.full]: hex(native.gem)});
  // Built: a shared library in lib/, the makefile and log in ext/.
  Object.assign(native.item.files, {
    'lib/native.so': hex('ELF'), 'ext/Makefile': hex('all:'), 'ext/mkmf.log': hex('log'), 'ext/conftest.rb': hex('x'),
  });
  let result = await rubygems.compare({scan: scanOf([native.item]), lock, store: registry.store()});
  assert.equal(result.passed, true, JSON.stringify(result));
  // Ruby source added next to it (loaded by require from the gem's lib/,
  // ahead of other gems): a failure, not build output.
  native.item.files['lib/json.rb'] = hex('system("id")');
  result = await rubygems.compare({scan: scanOf([native.item]), lock, store: registry.store()});
  assert.equal(result.passed, false);
  assert.deepEqual(result.findings[0].added, ['lib/json.rb']);
});
