'use strict';

const test = require('node:test');
const assert = require('node:assert/strict');
const {parseToml, TomlError} = require('../lib/toml');

const invalid = (text, pattern) => {
  assert.throws(() => parseToml(text), error => error instanceof TomlError && error.name === 'TomlError' && pattern.test(error.message), text);
};

test('uv.lock', () => {
  const lock = parseToml([
    'version = 1',
    'revision = 2',
    'requires-python = ">=3.12"',
    '',
    '[[package]]',
    'name = "certifi"',
    'version = "2024.8.30"',
    'source = { registry = "https://pypi.org/simple" }',
    'sdist = { url = "https://files.pythonhosted.org/packages/certifi-2024.8.30.tar.gz", hash = "sha256:bec9", size = 168507, upload-time = "2024-08-30T01:55:04.365Z" }',
    'wheels = [',
    '    { url = "https://files.pythonhosted.org/packages/certifi-2024.8.30-py3-none-any.whl", hash = "sha256:922820b5", size = 167321 },',
    ']',
    '',
    '[[package]]',
    'name = "app"',
    'version = "0.1.0"',
    'source = { editable = "." }',
    'dependencies = [',
    '    { name = "certifi" },',
    ']',
    '',
    '[package.optional-dependencies]',
    'dev = [',
    '    { name = "pytest" },',
    ']',
    '',
    '[package.metadata]',
    'requires-dist = [{ name = "certifi", specifier = ">=2024" }]',
    '',
  ].join('\n'));
  assert.equal(lock.version, 1);
  assert.equal(lock['requires-python'], '>=3.12');
  assert.equal(lock.package.length, 2);
  assert.deepEqual(lock.package[0].source, {registry: 'https://pypi.org/simple'});
  assert.equal(lock.package[0].sdist.size, 168_507);
  assert.equal(lock.package[0].sdist['upload-time'], '2024-08-30T01:55:04.365Z');
  assert.equal(lock.package[0].wheels[0].hash, 'sha256:922820b5');
  assert.deepEqual(lock.package[1].dependencies, [{name: 'certifi'}]);
  assert.deepEqual(lock.package[1]['optional-dependencies'], {dev: [{name: 'pytest'}]});
  assert.deepEqual(lock.package[1].metadata['requires-dist'], [{name: 'certifi', specifier: '>=2024'}]);
  assert.equal(Object.getPrototypeOf(lock), Object.prototype, 'plain objects');
  assert.equal(Object.getPrototypeOf(lock.package[0].source), Object.prototype);
});

test('Cargo.lock with Windows line endings', () => {
  const lock = parseToml([
    '# This file is automatically @generated by Cargo.',
    '# It is not intended for manual editing.',
    'version = 4',
    '',
    '[[package]]',
    'name = "app"',
    'version = "0.1.0"',
    'dependencies = [',
    ' "serde",',
    ' "local 0.1.0 (git+https://github.com/x/local#0123456789abcdef0123456789abcdef01234567)", # trailing comment',
    ']',
    '',
    '[[package]]',
    'name = "serde"',
    'version = "1.0.210"',
    'source = "registry+https://github.com/rust-lang/crates.io-index"',
    'checksum = "c8e3592472072e6e22e0a54d5904d9febf8508f65fb8552499a1abc7d1078c3a"',
  ].join('\r\n'));
  assert.equal(lock.version, 4);
  assert.deepEqual(lock.package.map(item => item.name), ['app', 'serde']);
  assert.equal(lock.package[0].dependencies.length, 2);
  assert.equal(lock.package[1].checksum.length, 64);
});

test('pyproject.toml', () => {
  const project = parseToml(`
[build-system]
requires = ["hatchling>=1.0"]
build-backend = "hatchling.build"

[project]
name = "example"
version = "1.0.0"
description = '''
A project
with a "quoted" word'''
authors = [{name = "Example", email = "dev@example.com"}]
dependencies = [
  "requests>=2",  # comment
  'tomli; python_version < "3.11"',
]

[project.scripts]
example = "example.cli:main"

[tool.uv.sources]
dep = { git = "https://github.com/x/dep", rev = "v1" }

[tool."hatch".version]
path = "example/__init__.py"
`);
  assert.equal(project['build-system']['build-backend'], 'hatchling.build');
  assert.equal(project.project.description, 'A project\nwith a "quoted" word');
  assert.deepEqual(project.project.dependencies, ['requests>=2', 'tomli; python_version < "3.11"']);
  assert.deepEqual(project.project.scripts, {example: 'example.cli:main'});
  assert.equal(project.tool.uv.sources.dep.rev, 'v1');
  assert.equal(project.tool.hatch.version.path, 'example/__init__.py');
});

test('strings: escapes, literal and multi-line forms', () => {
  const parsed = parseToml([
    String.raw`basic = "tab\t newline\n quote\" backslash\\ \b\f\r"`,
    String.raw`unicode = "\u00e9 \U0001F600"`,
    String.raw`literal = 'C:\Users\no\escapes'`,
    'multi = """\nfirst\nsecond"""',
    'multicrlf = """\r\nline"""',
    'inline = """same line"""',
    'folded = """\\\n    one \\  \n    two \\\r\n  three"""',
    String.raw`escaped = """a\tb"""`,
    'quotes1 = """ends with one""""',
    'quotes2 = """ends with two"""""',
    'multiliteral = \'\'\'\nraw \\n text\n\'\'\'',
    'literalquotes = \'\'\'it\'\'\'\'',
    'empty = ""',
    'emptyliteral = \'\'',
    '"quoted key" = 1',
    '\'literal key\' = 2',
    '"" = 3',
  ].join('\n'));
  assert.equal(parsed.basic, 'tab\t newline\n quote" backslash\\ \b\f\r');
  assert.equal(parsed.unicode, 'é 😀');
  assert.equal(parsed.literal, String.raw`C:\Users\no\escapes`);
  assert.equal(parsed.multi, 'first\nsecond');
  assert.equal(parsed.multicrlf, 'line');
  assert.equal(parsed.inline, 'same line');
  assert.equal(parsed.folded, 'one two three');
  assert.equal(parsed.escaped, 'a\tb');
  assert.equal(parsed.quotes1, 'ends with one"');
  assert.equal(parsed.quotes2, 'ends with two""');
  assert.equal(parsed.multiliteral, 'raw \\n text\n');
  assert.equal(parsed.literalquotes, 'it\'');
  assert.equal(parsed.empty, '');
  assert.equal(parsed.emptyliteral, '');
  assert.equal(parsed['quoted key'], 1);
  assert.equal(parsed['literal key'], 2);
  assert.equal(parsed[''], 3);
});

test('numbers, booleans, dates and times', () => {
  const parsed = parseToml(`
int = 42
positive = +17
negative = -5
underscored = 1_000_000
hex = 0xDEAD_beef
octal = 0o755
binary = 0b1101
negativehex = -0x10
float = 3.14
exponent = 6.626e-34
upper = 1E3
inf = inf
plusinf = +inf
neginf = -inf
nan = nan
yes = true
no = false
offset = 1979-05-27T07:32:00-08:00
utc = 1979-05-27T07:32:00.999Z
local = 1979-05-27 07:32:00
date = 1979-05-27
time = 07:32:00.5
`);
  assert.equal(parsed.int, 42);
  assert.equal(parsed.positive, 17);
  assert.equal(parsed.negative, -5);
  assert.equal(parsed.underscored, 1_000_000);
  assert.equal(parsed.hex, 0xDE_AD_BE_EF);
  assert.equal(parsed.octal, 0o755);
  assert.equal(parsed.binary, 13);
  assert.equal(parsed.negativehex, -16);
  assert.equal(parsed.float, 3.14);
  assert.equal(parsed.exponent, 6.626e-34);
  assert.equal(parsed.upper, 1000);
  assert.equal(parsed.inf, Infinity);
  assert.equal(parsed.plusinf, Infinity);
  assert.equal(parsed.neginf, -Infinity);
  assert.ok(Number.isNaN(parsed.nan));
  assert.equal(parsed.yes, true);
  assert.equal(parsed.no, false);
  assert.equal(parsed.offset, '1979-05-27T07:32:00-08:00');
  assert.equal(parsed.utc, '1979-05-27T07:32:00.999Z');
  assert.equal(parsed.local, '1979-05-27 07:32:00');
  assert.equal(parsed.date, '1979-05-27');
  assert.equal(parsed.time, '07:32:00.5');
});

test('arrays, inline tables, dotted keys and tables', () => {
  const parsed = parseToml(`
empty = []
nested = [[1, 2], ["a"], []]
trailing = [
  1,
  # a comment line
  2,
]
emptyinline = {}
point = { x = 1, y.z = 2 }
site."google.com" = true
a . b . c = 1
a.d = 2

[table]
key = "value"

[table.sub]

[[fruits]]
name = "apple"

[fruits.physical]
color = "red"

[[fruits.varieties]]
name = "red delicious"

[[fruits]]
name = "banana"

[fruit]
apple.color = "red"
apple.taste.sweet = true

[fruit.apple.texture]
smooth = true

[x.y.z.w]
[x]
`);
  assert.deepEqual(parsed.empty, []);
  assert.deepEqual(parsed.nested, [[1, 2], ['a'], []]);
  assert.deepEqual(parsed.trailing, [1, 2]);
  assert.deepEqual(parsed.emptyinline, {});
  assert.deepEqual(parsed.point, {x: 1, y: {z: 2}});
  assert.deepEqual(parsed.site, {'google.com': true});
  assert.deepEqual(parsed.a, {b: {c: 1}, d: 2});
  assert.deepEqual(parsed.table, {key: 'value', sub: {}});
  assert.deepEqual(parsed.fruits, [
    {name: 'apple', physical: {color: 'red'}, varieties: [{name: 'red delicious'}]},
    {name: 'banana'},
  ]);
  assert.deepEqual(parsed.fruit, {apple: {color: 'red', taste: {sweet: true}, texture: {smooth: true}}});
  assert.deepEqual(parsed.x, {y: {z: {w: {}}}});
  assert.deepEqual(parseToml(''), {});
  assert.deepEqual(parseToml('# only a comment'), {});
  assert.deepEqual(parseToml('\n\n  \t\n'), {});
});

test('syntax errors name the line', () => {
  invalid('a = 1\nb = "unterminated\n', /unterminated string \(line 2\)/);
  invalid('a = "unterminated', /unterminated string/);
  invalid('a = """never closed', /unterminated string/);
  invalid('a = """folded at the end \\\n  ', /unterminated string \(line 2\)/);
  invalid(String.raw`a = "\x"`, /invalid escape \\x/);
  invalid(String.raw`a = "\u12"`, /invalid unicode escape/);
  invalid(String.raw`a = "\u12G4"`, /invalid unicode escape/);
  invalid('= 1', /expected a key/);
  invalid('a 1', /expected =/);
  invalid('a = 1 2', /unexpected "2"/);
  invalid('a = 1\r', /unexpected "\\r"/);
  invalid('a = @', /invalid value starting "@"/);
  invalid('a = [1 2]', /expected , or ] in array/);
  invalid('a = {b 1}', /expected = in inline table/);
  invalid('a = {b = 1 c = 2}', /expected , or } in inline table/);
  invalid('[a', /expected ] after table name/);
  invalid('[[a]', /expected ] after table name/);
});

test('redefinitions are errors', () => {
  invalid('a = 1\na = 2', /duplicate key a/);
  invalid('a = {b = 1, b = 2}', /duplicate key b/);
  invalid('a = 1\na.b = 2', /cannot extend a\.b/);
  invalid('a = {b = 1}\na.c = 2', /cannot extend a\.c/);
  invalid('[a]\n[a]', /table a is defined twice/);
  invalid('a = 1\n[a]', /cannot redefine a/);
  invalid('a = {}\n[a.b]', /cannot redefine a\.b/);
  invalid('a = 1\n[[a]]', /cannot redefine a as an array of tables/);
  invalid('[a]\n[[a]]', /cannot redefine a as an array of tables/);
  invalid('a = [{b = 1}]\n[[a]]', /cannot redefine a as an array of tables/);
  invalid('a = [1]\n[[a]]', /cannot redefine a as an array of tables/);
  invalid('a = [1]\n[a.b]', /cannot redefine a\.b/);
  // Tables defined by a header may not be extended with dotted keys, and
  // tables defined by dotted keys may not be reopened by a header.
  invalid('[a.b.c]\nz = 9\n[a]\nb.c.t = 1', /cannot extend b\.c\.t/);
  invalid('[a.b]\nx = 1\n[a]\nb.c = 1', /cannot extend b\.c/);
  invalid('[fruit]\napple.color = "red"\n[fruit.apple]', /table fruit\.apple is defined twice/);
  invalid('a.b = 1\n[a]', /table a is defined twice/);
});

test('a key named __proto__ is an ordinary key', () => {
  // Another TOML reader sees a table named "__proto__"; so must this one,
  // rather than a document whose other keys it silently inherits.
  const parsed = parseToml('[__proto__]\npackage = [{name = "evil"}]\n\n[a]\n"__proto__" = {x = 1}\n');
  assert.deepStrictEqual(Object.keys(parsed), ['__proto__', 'a']);
  assert.strictEqual(Object.getPrototypeOf(parsed), Object.prototype);
  assert.strictEqual(parsed.package, undefined);
  assert.deepStrictEqual(Object.getOwnPropertyDescriptor(parsed, '__proto__').value, {package: [{name: 'evil'}]});
  assert.strictEqual(Object.getPrototypeOf(parsed.a), Object.prototype);
  assert.strictEqual(parsed.a.x, undefined);
  assert.deepStrictEqual(Object.keys(parsed.a), ['__proto__']);
});
